#spring.application.name=ms-produit
#spring.cloud.config.profile=dev
#spring.cloud.config.uri=http://localhost:8888
#spring.cloud.config.enabled=false

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true



spring:
  config:
    import: optional:configserver:http://localhost:8888/
    #uri: http://localhost:8888
  application:
    name: ms-produit  # Application name

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: my-group
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: tn.esprit.dto




