spring:
  config:
    import: optional:configserver:http://localhost:8888/
    #uri: http://localhost:8888
  application:
    name: ms-stock
  kafka:
    bootstrap-servers: localhost:9094

    consumer:
      group-id: my-group
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: tn.esprit.dto